Unify module design
lablabs/terraform-aws-eks-metrics-server pull request #8
Opened 2022-05-11 12:55 UTC by MonolithProjects

This PR contains:
- TF module refactoring to align with LARA unified desing
- Community standards/experience improvements

2022-06-22 08:13 UTC, MonolithProjects commented
@dojci added the outputs

2022-06-27 11:19 UTC, tomas-balaz commented on argo.tf
>  resource "helm_release" "argocd_application" {
rename `argocd_application` to `argo_application`

2022-06-27 11:21 UTC, tomas-balaz commented on argo.tf
>  resource "helm_release" "argocd_application" {
rename `argocd_application` to `argo_application`

2022-06-28 14:52 UTC, tomas-balaz commented on README.md
>  [GitHub Actions documentation](https://docs.github.com/en/actions) for further
[\[GitHub Actions workflow\]\(.github/workflows/main.yml\)](https://github.com/lablabs/terraform-aws-eks-metrics-server/pull/8/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R141) link is not working (file not found)

2022-06-29 19:45 UTC, dojci requested changes

2022-06-29 19:45 UTC, dojci commented on examples/basic/main.tf
> +
please create a testing matrix that is used also for dummy testing with terraform plan in pipelines. It would be nice to have tests on all installation paths: helm, helm+argo, argo.

2022-06-30 13:07 UTC, merged